/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jozua Palandi
 */
public class NewJFrame extends javax.swing.JFrame {
int billAmount=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBoxBurger = new javax.swing.JCheckBox();
        jCheckBoxHotDog = new javax.swing.JCheckBox();
        jCheckBoxPizza = new javax.swing.JCheckBox();
        jLabelResponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Harga Makanan");

        jCheckBoxBurger.setText("Burger Rp. 16000");
        jCheckBoxBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBurgerActionPerformed(evt);
            }
        });

        jCheckBoxHotDog.setText("Hot Dog Rp. 20000");
        jCheckBoxHotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHotDogActionPerformed(evt);
            }
        });

        jCheckBoxPizza.setText("Pizza Rp. 45000");
        jCheckBoxPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPizzaActionPerformed(evt);
            }
        });

        jLabelResponse.setText("Total Harga : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxHotDog)
                            .addComponent(jCheckBoxBurger)
                            .addComponent(jCheckBoxPizza)
                            .addComponent(jLabelResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxBurger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxHotDog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxPizza)
                .addGap(18, 18, 18)
                .addComponent(jLabelResponse)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBurgerActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxBurger.isSelected()) {
            billAmount=billAmount+16000;
        } else {
            billAmount=billAmount-16000;
        }
        jLabelResponse.setText("Total Harga : Rp. " + String.valueOf(billAmount));
    }//GEN-LAST:event_jCheckBoxBurgerActionPerformed

    private void jCheckBoxHotDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHotDogActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxHotDog.isSelected()) {
            billAmount=billAmount+20000;
        } else {
            billAmount=billAmount-20000;
        }
        jLabelResponse.setText("Total Harga : Rp. " + String.valueOf(billAmount));
    }//GEN-LAST:event_jCheckBoxHotDogActionPerformed

    private void jCheckBoxPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPizzaActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxPizza.isSelected()) {
            billAmount=billAmount+45000;
        } else {
            billAmount=billAmount-45000;
        }
        jLabelResponse.setText("Total Harga : Rp. " + String.valueOf(billAmount));
    }//GEN-LAST:event_jCheckBoxPizzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxBurger;
    private javax.swing.JCheckBox jCheckBoxHotDog;
    private javax.swing.JCheckBox jCheckBoxPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResponse;
    // End of variables declaration//GEN-END:variables
}
